#!/usr/bin/env node
/**
 * Generates src/lib/generated/site.ts and src/lib/generated/content.ts from
 * content/data/site.json and content/data/content.json.
 *
 * content/data/*.json is the single source of truth for editable site config and
 * profile data. The admin panel writes these files; run `npm run generate:content`
 * (or `npm run build`, which runs it first) to compile them into the TS modules
 * that the rest of the app imports through @/lib/site and @/lib/data.
 */
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (name) =>
  JSON.parse(readFileSync(join(root, "content", "data", name), "utf8"));

const SITE_REQUIRED = [
  "name", "shortName", "tagline", "title", "description", "url", "location",
  "email", "availability", "calendly", "formspree", "socials", "navLinks",
];
const CONTENT_REQUIRED = [
  "profile", "stats", "education", "experience", "publications", "awards",
  "certifications", "skills", "languages", "projects", "services", "domains",
];

function requireKeys(obj, keys, file) {
  for (const k of keys) {
    if (!(k in obj)) throw new Error(`${file} is missing required key "${k}"`);
  }
}

/** JSON.stringify a value so it is valid JS literal syntax */
const lit = (v) => JSON.stringify(v);

const AVAILABLE_ICONS = [
  "Brain", "Cpu", "FlaskConical", "Hexagon", "Magnet", "Network", "ScanLine", "Sigma", "Sparkles", "Workflow",
];

function iconNames(json) {
  const names = new Set();
  for (const d of json.domains) if (typeof d.icon === "string") names.add(d.icon);
  for (const s of json.services) if (typeof s.icon === "string") names.add(s.icon);
  for (const n of names) {
    if (!AVAILABLE_ICONS.includes(n)) {
      throw new Error(`Unknown icon name "${n}" in content/data/content.json. Available: ${AVAILABLE_ICONS.join(", ")}`);
    }
  }
  return names;
}

function iconMap(names, indent = "  ") {
  const rows = [...names].sort().map((n) => `${indent}${n},`);
  return rows.join("\n");
}

function renderDomains(json) {
  return `export const domains: ResearchDomain[] = [${json.domains
    .map((d) => `\n  {\n    id: ${lit(d.id)},\n    label: ${lit(d.label)},\n    short: ${lit(d.short)},\n    blurb: ${lit(d.blurb)},\n    level: ${lit(d.level)},\n    heat: ${lit(d.heat)},\n    color: ${lit(d.color)},\n    icon: I.${d.icon},\n    keywords: ${lit(d.keywords)},\n  }`)
    .join(",")}\n];`;
}

function renderServices(json) {
  return `export const services = [${json.services
    .map((s) => `\n  {\n    icon: I.${s.icon},\n    title: ${lit(s.title)},\n    blurb: ${lit(s.blurb)},\n  }`)
    .join(",")}\n];`;
}

function renderArray(name, type, value) {
  if (type) return `export const ${name}: ${type}[] = ${lit(value)};`;
  return `export const ${name} = ${lit(value)};`;
}

function buildContent(json) {
  const icons = iconNames(json);
  const header = `// AUTO-GENERATED by scripts/generate-content.mjs — do not edit.
// Source of truth: content/data/content.json (managed via the /admin panel).
import type { ResearchDomain, TimelineItem, Publication, SkillGroup, Project } from "../content-types";
import { Brain, Cpu, FlaskConical, Hexagon, Magnet, Network, ScanLine, Sigma, Sparkles, Workflow } from "lucide-react";`;

  const parts = [header];

  parts.push(`
const I = {
${iconMap(icons)}
  };`);

  parts.push(`\n${renderDomains(json)}\n`);
  parts.push(`export const marqueeDomains = domains.map((d) => d.label);\n`);
  parts.push(`export const profile = ${lit(json.profile)};\n`);
  parts.push(renderArray("stats", null, json.stats));
  parts.push(renderArray("education", "TimelineItem", json.education));
  parts.push(renderArray("experience", "TimelineItem", json.experience));
  parts.push(renderArray("publications", "Publication", json.publications));
  parts.push(renderArray("awards", null, json.awards));
  parts.push(renderArray("certifications", null, json.certifications));
  parts.push(renderArray("skills", "SkillGroup", json.skills));
  parts.push(renderArray("languages", null, json.languages));
  parts.push(`export const projects: Project[] = ${lit(json.projects)};\n`);
  parts.push(`${renderServices(json)}\n`);

  return parts.join("\n");
}

function buildSite(json) {
  const { navLinks, socials, ...rest } = json;
  const site = { ...rest, socials };
  return `// AUTO-GENERATED by scripts/generate-content.mjs — do not edit.
// Source of truth: content/data/site.json (managed via the /admin panel).
export const site = ${lit(site)} as const;

export const navLinks = ${lit(navLinks)} as const;
`;
}

const siteJson = read("site.json");
const contentJson = read("content.json");
requireKeys(siteJson, SITE_REQUIRED, "site.json");
requireKeys(contentJson, CONTENT_REQUIRED, "content.json");

const outDir = join(root, "src", "lib", "generated");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "site.ts"), buildSite(siteJson), "utf8");
writeFileSync(join(outDir, "content.ts"), buildContent(contentJson), "utf8");

console.log(`✓ generated src/lib/generated/site.ts and src/lib/generated/content.ts`);